FROM openjdk:11

LABEL "Developer"="Jairo Nascimento"

LABEL "Objetivo"="Deploy API MicroService with Docker and Spring Boot"

WORKDIR /app

COPY target/Product-Microservice-1.0.0.jar Product-Microservice-1.0.0.jar

EXPOSE 8080

CMD ["java","-jar", "Product-Microservice-1.0.0.jar"]